Repository julianMondragon/TAS360, pull requests merged in 2024-09, with the labels that each got.

#37 Agregar encriptación de la contraseña al metodo "Crear y Editar Usuario"
  Controllers/UserController.cs
  Views/User/Create.cshtml
Labels: good first issue, Features

#35 Export table tickets
  Controllers/TicketsController.cs
  Models/ViewModel/TicketViewModel.cs
  Prototipo_Tabla/Lista_de_tickets_.xlsx
  TAS360.csproj
  Views/Tickets/Index.cshtml
  Views/Tickets/IndexWithFilter.cshtml
Labels: good first issue

#36 Modulo Usuario, Roles y Permisos
  Controllers/Calculo_FCVController.cs
  Controllers/DocumentacionController.cs
  Controllers/LSAController.cs
  Controllers/Roles_and_PrivilegeController.cs
  Controllers/TablaCubController.cs
  Controllers/TicketsController.cs
  Models/ViewModel/ModuloViewModel.cs
  Models/ViewModel/OperacionViewModel.cs
  Models/ViewModel/Rol_OperacionViewModel.cs
  Models/ViewModel/RolesPrivilegesViewModel.cs
  Models/ViewModel/RollViewModel.cs
  TAS360.csproj
  Views/Roles_and_Privilege/AddModule.cshtml
  Views/Roles_and_Privilege/AddOperation.cshtml
  Views/Roles_and_Privilege/AddRol.cshtml
  Views/Roles_and_Privilege/AddRol_Operacion.cshtml
  Views/Roles_and_Privilege/Index.cshtml
  Views/Shared/_Layout.cshtml
  Web.config
Labels: Features
