Repository julianMondragon/TAS360, pull requests merged in 2024-08, with the labels that each got.

#16 Ultima revisión antes de hacer Deploy
  App_Start/RouteConfig.cs
  Controllers/AccesoController.cs
  Controllers/HomeController.cs
  Controllers/TicketsController.cs
  Models/ViewModel/TicketViewModel.cs
  Views/Shared/_Layout.cshtml
  Views/Shared/_LayoutReport.cshtml
  Views/Tickets/IndexWithFilter.cshtml
  Views/Tickets/ShowTicket.cshtml
Labels: Deploy

#28 Fix bug
  Views/Acceso/Login.cshtml
Labels: bug

#30 Pull request Divisor_comentarios
  Controllers/TicketsController.cs
Labels: good first issue

#31 Feature new login page
  Content/bootstrap.css
  Views/Acceso/Login.cshtml
  Views/Acceso/RecuperarContraseña.cshtml
Labels: bug

#33 Se corrige BUG de login page y se actualiza estilo de recuperar contr…
  Content/bootstrap.css
  Views/Acceso/Login.cshtml
  Views/Acceso/RecuperarContraseña.cshtml
Labels: bug
