Repository julianMondragon/TAS360, pull requests merged in 2025-04, with the labels that each got.

#67 66 mas tiempo de sesión
  Controllers/HomeController.cs
  Views/Shared/_Layout.cshtml
Labels: wontfix

#69 58 crud faltantes en el modulo roles y privilegios
  Controllers/Roles_and_PrivilegeController.cs
  Controllers/UserController.cs
  Models/Operacion.cs
  Models/ViewModel/ListUsuarioViewModel.cs
  Models/ViewModel/OperacionViewModel.cs
  Models/ViewModel/RolesPrivilegesViewModel.cs
  TAS360.csproj
  Views/Roles_and_Privilege/EditModulos.cshtml
  Views/Roles_and_Privilege/EditOperation.cshtml
  Views/Roles_and_Privilege/EditRol.cshtml
  Views/Roles_and_Privilege/Index.cshtml
  Views/User/Edit.cshtml
  Views/User/Index.cshtml
  Web.config
Labels: Features

#75 Fix bugs sprint 4
  Backup_Database/Sprint_4/SQLQuery1 (Roles y operaciones).sql
  Backup_Database/Sprint_4/SQLQuery2 (Crea tabla usr_perfil).sql
  Backup_Database/Sprint_4/SQLQuery3 (Crea registro en usr_profile de User).sql
  Backup_Database/Sprint_4/SQLQuery4 (trigger para usr_profile de nuevo user).sql
  Backup_Database/Sprint_4/SQLQuery_cambio_nombre_roles.sql
  Controllers/AccesoController.cs
  Controllers/HomeController.cs
  Controllers/Roles_and_PrivilegeController.cs
  Controllers/TablaCubController.cs
  Controllers/TerminalController.cs
  Controllers/TicketsController.cs
  Controllers/UserController.cs
  Models/Operacion.cs
  Models/ViewModel/FilterTicketsViewModel.cs
  Models/ViewModel/ListUsuarioViewModel.cs
  Models/ViewModel/OperacionViewModel.cs
  Models/ViewModel/RolesPrivilegesViewModel.cs
  TAS360.csproj
  Views/Acceso/Login.cshtml
  Views/LSA/SLAReport.cshtml
  Views/Profile.cs
  Views/Roles_and_Privilege/EditModulos.cshtml
  Views/Roles_and_Privilege/EditOperation.cshtml
  Views/Roles_and_Privilege/EditRol.cshtml
  Views/Roles_and_Privilege/Index.cshtml
  Views/Shared/_Layout.cshtml
  Views/Shared/_LayoutReport.cshtml
  Views/Tickets/EditTicket.cshtml
  Views/Tickets/Filter_Tickets.cshtml
  Views/Tickets/Index.cshtml
  Views/Tickets/IndexWithFilter.cshtml
  Views/Tickets/ShowTicket.cshtml
  Views/User/Edit.cshtml
  Views/User/Index.cshtml
  Web.config
Labels: bug
